// Write the Competitive Exams page's panels into exams/index.html.
//
// The page used to ship an empty #exam-root that js/exams-page.js filled in the browser,
// one panel at a time as a visitor opened it. Search engines never open an accordion, and
// crawlers that run no JavaScript at all (Bing's first pass, AI answer engines, WhatsApp
// and social previews) got even less: the UPSC, RAS, SSC and NCERT material under the six
// headings was invisible to all of them. This renders the same markup at build time with
// the same code the browser runs, so the two cannot drift.
//
// UPSC, RAS, the NCERT roadmap and the SSC subjects each get a page of their own under
// /exams/, because one URL carrying every exam competed with itself for every exam search
// and none of them could rank. The hub keeps the short panels and links to the four pages.
//
//   node tools/build-exams.mjs          rewrite exams/index.html and the exam pages
//   node tools/build-exams.mjs --check  fail if any of them is stale
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { applyChrome } from "./build-chrome.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PAGE = path.join(ROOT, "exams", "index.html");
const START = "<!-- pf:exams:start (generated by tools/build-exams.mjs; edit js/data/exams.js) -->";
const END = "<!-- pf:exams:end -->";
const check = process.argv.includes("--check");
const ORIGIN = "https://pigsfield.com";

/** Hand-written framing for each exam page. The resources come from js/data/exams.js. */
export const EXAM_PAGES = [
  {
    key: "ias",
    slug: "upsc",
    card: "Prelims, CSAT and Mains, paper by paper.",
    name: "UPSC",
    title: "Free UPSC Syllabus Guide: Prelims & Mains Resources | Pigsfield",
    h1: "UPSC syllabus with free courses, marathons and books for every paper",
    description: "The UPSC Civil Services syllabus paper by paper, with free courses, revision marathons, books and official previous papers for each topic.",
    intro: [
      "The Civil Services Examination has three stages: Prelims (General Studies Paper I and the qualifying CSAT paper), Mains (nine descriptive papers, seven of which count towards merit) and the interview. This page follows that structure paper by paper.",
      "Under each topic you will find the official syllabus wording, then a free full course for learning it, a revision marathon for the last weeks, and books for focused practice. Start with the NCERT foundation, because much of Prelims General Studies is built on the Class 6 to 12 textbooks, then move to one standard book per subject and practise with official previous papers.",
      "Everything links to its original provider; Pigsfield hosts none of it. UPSC sets the syllabus and pattern and can change them with each notification, so confirm them on upsc.gov.in before you plan your year."
    ]
  },
  {
    key: "ras",
    slug: "ras",
    card: "Prelims and Mains, with Rajasthan GK.",
    name: "RAS",
    title: "RAS Syllabus Guide: Free RPSC Prelims & Mains Prep | Pigsfield",
    h1: "RAS syllabus with free courses, marathons and books for Prelims and Mains",
    description: "The RPSC RAS syllabus for Prelims and Mains, with free courses, revision marathons, books and RPSC and RSSB previous papers for each topic.",
    intro: [
      "The Rajasthan Administrative Services exam, conducted by the Rajasthan Public Service Commission as the RAS/RTS Combined Competitive Examination, has a single objective Prelims paper, four descriptive Mains papers and an interview.",
      "Rajasthan's history, art and culture, geography and economy carry real weight at every stage, alongside the national General Studies syllabus it shares with UPSC. This page sets out the syllabus paper by paper, with a free course, a revision marathon and books under each topic. A practical order is NCERT books first, then Rajasthan-specific material, then previous papers to see how questions are actually framed.",
      "All links open their original provider. Check the current notification on rpsc.rajasthan.gov.in, because the pattern and syllabus can change."
    ]
  },
  {
    key: "roadmap",
    slug: "ncert-books-for-upsc-ras-ssc",
    card: "Which class, which book, for which exam.",
    name: "NCERT roadmap",
    title: "NCERT Books for UPSC, RAS & SSC: Class-wise Roadmap | Pigsfield",
    h1: "Which NCERT books to read for UPSC, RAS and SSC, class by class",
    description: "Which NCERT classes and books UPSC, RAS and SSC expect for history, geography, polity, economy, science and more, compared subject by subject.",
    intro: [
      "Most general studies questions in UPSC, RAS and SSC rest on the same school textbooks. The difference is how far up each exam goes. The table compares, subject by subject, which NCERT classes each exam expects and which titles or chapters to read first: history, geography, polity, economy, general science, environment, art and culture, and society.",
      "A sensible order is to read the Class 6 to 10 books quickly for vocabulary and basics, then the Class 11 and 12 books slowly, making short notes you can revise. NCERT textbooks are free to read and download from the official NCERT site, linked above the table.",
      "Treat this as a reading plan rather than a syllabus: each exam's official notification remains the final word."
    ]
  },
  {
    key: "common",
    slug: "ssc",
    card: "Maths, reasoning, English and GK.",
    name: "SSC",
    title: "Free SSC Preparation: Maths, Reasoning, English & GK | Pigsfield",
    h1: "Free SSC courses for maths, reasoning, English, GK and current affairs",
    description: "Free courses, revision marathons and books for SSC CGL and CHSL subjects: quantitative aptitude, reasoning, English, general awareness and computers.",
    intro: [
      "SSC CGL, CHSL and most other recruitment exams test the same core subjects: quantitative aptitude, reasoning, English, general awareness and computer awareness. This page gathers free courses, revision marathons and books for each, with banking-specific options where they differ, plus Hindi, general science, polity, geography, environment, economy, static GK and current affairs.",
      "The history section adds world and Indian history classes that also serve UPSC and state exams. A workable routine is a daily slot for maths and reasoning, where marks come from practice rather than reading, and a weekly cycle through the general awareness subjects.",
      "Every link opens its original provider. Check the current notification on ssc.gov.in for the exact pattern of the exam you are taking."
    ]
  }
];
export const EXAM_ROUTES = EXAM_PAGES.map((page) => `/exams/${page.slug}/`);
const SPLIT_KEYS = EXAM_PAGES.map((page) => page.key);

const esc = (value) => String(value == null ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const read = (file) => fs.readFileSync(path.join(ROOT, file), "utf8");

/** A marked block of js/site.js, so the helpers come from the file the browser runs. */
function siteBlock(site, name) {
  const start = site.indexOf(`/* pf:${name}:start`);
  const end = site.indexOf(`/* pf:${name}:end */`);
  if (start < 0 || end <= start) throw new Error(`js/site.js no longer marks its pf:${name} block`);
  return site.slice(start, end);
}

/** A named function or PF assignment lifted out of js/site.js by its opening line. */
function siteFunction(site, opening) {
  const start = site.indexOf(opening);
  if (start < 0) throw new Error(`js/site.js no longer contains "${opening}"`);
  const end = site.indexOf("\n  }", start);
  return site.slice(start, end + 4);
}

function examMarkup() {
  const site = read("js/site.js");
  const context = vm.createContext({
    window: { PF: {} },
    document: { readyState: "loading", addEventListener() {} },
    URL
  });
  vm.runInContext(
    "const PF = window.PF;\n" +
    `${siteFunction(site, "function escapeHtml(value) {")}\nPF.escapeHtml = escapeHtml;\n` +
    `${siteFunction(site, "PF.slug = function (value) {")};\n` +
    `${siteBlock(site, "source-marks")}\n` +
    "PF.classifySource = classifySource; PF.sourceBrand = sourceBrand; PF.sourceMark = sourceMark;",
    context
  );
  new vm.Script(read("js/data/exams.js")).runInContext(context);
  new vm.Script(read("js/exams-page.js")).runInContext(context);
  const { PF, PF_DATA } = context.window;
  if (typeof PF.examMarkup !== "function") throw new Error("js/exams-page.js no longer exposes PF.examMarkup");
  return PF.examMarkup(PF, PF_DATA.exams);
}

/** The hub: a card for each exam page, then the panels that stay on it. */
export function renderExams() {
  const markup = examMarkup();
  const cards = EXAM_PAGES.map((page) => `<a class="topic-card" href="${page.slug}/"><span class="topic-card-name">${esc(page.h1)}</span><span class="topic-card-note">${esc(page.description)}</span></a>`).join("");
  const keys = markup.panelDefinitions.map((definition) => definition.key).filter((key) => !SPLIT_KEYS.includes(key));
  return `<div class="topic-index exam-guides">${cards}</div>${markup.prerendered(keys)}`;
}

export function renderExamPage(page) {
  const markup = examMarkup();
  const route = `/exams/${page.slug}/`;
  const canonical = `${ORIGIN}${route}`;
  const graph = [
    { "@type": "CollectionPage", "@id": `${canonical}#webpage`, url: canonical, name: page.h1, description: page.description, inLanguage: "en-IN", isPartOf: { "@id": `${ORIGIN}/#website` }, publisher: { "@id": `${ORIGIN}/#organization` }, breadcrumb: { "@id": `${canonical}#breadcrumb` } },
    { "@type": "BreadcrumbList", "@id": `${canonical}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Pigsfield", item: `${ORIGIN}/` },
      { "@type": "ListItem", position: 2, name: "Competitive Exams", item: `${ORIGIN}/exams/` },
      { "@type": "ListItem", position: 3, name: page.name, item: canonical }
    ] }
  ];
  const siblings = EXAM_PAGES.filter((other) => other !== page).map((other) => `<a class="button ghost" href="../${other.slug}/">${esc(other.name)}</a>`).join("");
  const image = `${ORIGIN}/assets/og/exams-${page.slug}.jpg`;
  const html = `<!doctype html>
<html lang="en-IN" data-base="../../">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="referrer" content="strict-origin-when-cross-origin"><meta name="theme-color" content="#f4f1e8">
  <title>${esc(page.title)}</title>
  <meta name="description" content="${esc(page.description)}">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
  <link rel="canonical" href="${canonical}"><link rel="icon" href="../../assets/pigsfield-icon-192.png" type="image/png" sizes="192x192"><link rel="manifest" href="../../manifest.json">
  <meta property="og:type" content="website"><meta property="og:site_name" content="Pigsfield"><meta property="og:locale" content="en_IN"><meta property="og:title" content="${esc(page.title)}"><meta property="og:description" content="${esc(page.description)}"><meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${image}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Pigsfield ${esc(page.name)} preparation guide"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(page.title)}"><meta name="twitter:description" content="${esc(page.description)}"><meta name="twitter:image" content="${image}"><meta name="twitter:image:alt" content="Pigsfield ${esc(page.name)} preparation guide">
  <link rel="preload" href="../../assets/google-sans-flex-latin.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="../../css/site.css">
  <script defer src="../../js/site.js"></script><script defer src="../../js/player.js"></script><script defer src="../../js/exams-page.js"></script>
  <script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@graph": graph })}</script>
</head>
<body data-page="exams">
  <a class="skip-link" href="#main-content">Skip to content</a><header data-site-header></header>
  <main id="main-content">
    <div class="container breadcrumbs"><ol><li><a href="../../">Home</a></li><li><a href="../">Competitive Exams</a></li><li aria-current="page">${esc(page.name)}</li></ol></div>
    <section class="page-hero"><div class="container"><span class="eyebrow">${esc(page.name)}</span><h1>${esc(page.h1)}</h1>${page.intro.map((paragraph) => `<p class="lede">${esc(paragraph)}</p>`).join("")}</div></section>
    <section class="explorer"><div class="container">
      <div class="ai-privacy"><strong>Always confirm the notification:</strong><span>Syllabus, eligibility, dates and patterns can change. Use this as a study map, then verify current requirements on the official exam website.</span></div>
      <div id="exam-root" data-exam-page="${esc(page.slug)}">${markup.prerendered([page.key], true)}</div>
    </div></section>
    <section class="section alt"><div class="container">
      <h2>More exam guides</h2>
      <nav class="topic-siblings" aria-label="Related exam guides">${siblings}</nav>
      <p><a class="button ghost" href="../">All competitive exam resources</a></p>
    </div></section>
  </main>
  <footer data-site-footer></footer>
</body>
</html>
`;
  return applyChrome(html).replace(/\?v=[a-f0-9]{12}(?=")/g, "");
}

const sameYear = (html) => html.replace(/<span data-year>\d{4}<\/span>/g, "<span data-year></span>").replace(/\?v=[a-f0-9]{12}(?=")/g, "");

function build() {
  const page = fs.readFileSync(PAGE, "utf8");
  const block = `${START}${renderExams()}${END}`;
  const start = page.indexOf(START);
  const end = page.indexOf(END);
  let next;
  if (start >= 0 && end > start) next = page.slice(0, start) + block + page.slice(end + END.length);
  else if (page.includes('<div id="exam-root"></div>')) next = page.replace('<div id="exam-root"></div>', `<div id="exam-root">${block}</div>`);
  else throw new Error("exams/index.html has neither generated exam panels nor an empty #exam-root to fill");
  const stale = [];
  if (next !== page) {
    if (check) stale.push("exams/index.html");
    else fs.writeFileSync(PAGE, next);
  }
  for (const examPage of EXAM_PAGES) {
    const file = path.join(ROOT, "exams", examPage.slug, "index.html");
    const html = renderExamPage(examPage);
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    if (sameYear(current) === sameYear(html)) continue;
    if (check) stale.push(path.relative(ROOT, file));
    else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, html);
    }
  }
  if (check) {
    if (stale.length) {
      console.error(`Exam pages are stale: ${stale.join(", ")}. Run: npm run build:exams`);
      process.exit(1);
    }
    console.log("Exam panels and pages are current.");
    return;
  }
  console.log(`Wrote exams/index.html and ${EXAM_PAGES.length} exam pages.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) build();
