// Write the Competitive Exams page's panels into exams/index.html.
//
// The page used to ship an empty #exam-root that js/exams-page.js filled in the browser,
// one panel at a time as a visitor opened it. Search engines never open an accordion, and
// crawlers that run no JavaScript at all (Bing's first pass, AI answer engines, WhatsApp
// and social previews) got even less: the UPSC, RAS, SSC and NCERT material under the six
// headings was invisible to all of them. This renders the same markup at build time with
// the same code the browser runs, so the two cannot drift.
//
//   node tools/build-exams.mjs          rewrite exams/index.html
//   node tools/build-exams.mjs --check  fail if exams/index.html is stale
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PAGE = path.join(ROOT, "exams", "index.html");
const START = "<!-- pf:exams:start (generated by tools/build-exams.mjs; edit js/data/exams.js) -->";
const END = "<!-- pf:exams:end -->";
const check = process.argv.includes("--check");

const read = (file) => fs.readFileSync(path.join(ROOT, file), "utf8");

/** A marked block of js/site.js, so the helpers come from the file the browser runs. */
function siteBlock(site, name) {
  const start = site.indexOf(`/* pf:${name}:start`);
  const end = site.indexOf(`/* pf:${name}:end */`);
  if (start < 0 || end <= start) throw new Error(`js/site.js no longer marks its pf:${name} block`);
  return site.slice(start, end);
}

/** A named function or PF assignment lifted out of js/site.js by its opening line. */
function siteFunction(site, opening) {
  const start = site.indexOf(opening);
  if (start < 0) throw new Error(`js/site.js no longer contains "${opening}"`);
  const end = site.indexOf("\n  }", start);
  return site.slice(start, end + 4);
}

export function renderExams() {
  const site = read("js/site.js");
  const context = vm.createContext({
    window: { PF: {} },
    document: { readyState: "loading", addEventListener() {} },
    URL
  });
  vm.runInContext(
    "const PF = window.PF;\n" +
    `${siteFunction(site, "function escapeHtml(value) {")}\nPF.escapeHtml = escapeHtml;\n` +
    `${siteFunction(site, "PF.slug = function (value) {")};\n` +
    `${siteBlock(site, "source-marks")}\n` +
    "PF.classifySource = classifySource; PF.sourceBrand = sourceBrand; PF.sourceMark = sourceMark;",
    context
  );
  new vm.Script(read("js/data/exams.js")).runInContext(context);
  new vm.Script(read("js/exams-page.js")).runInContext(context);
  const { PF, PF_DATA } = context.window;
  if (typeof PF.examMarkup !== "function") throw new Error("js/exams-page.js no longer exposes PF.examMarkup");
  return PF.examMarkup(PF, PF_DATA.exams).prerendered();
}

function build() {
  const page = fs.readFileSync(PAGE, "utf8");
  const block = `${START}${renderExams()}${END}`;
  const start = page.indexOf(START);
  const end = page.indexOf(END);
  let next;
  if (start >= 0 && end > start) next = page.slice(0, start) + block + page.slice(end + END.length);
  else if (page.includes('<div id="exam-root"></div>')) next = page.replace('<div id="exam-root"></div>', `<div id="exam-root">${block}</div>`);
  else throw new Error("exams/index.html has neither generated exam panels nor an empty #exam-root to fill");
  if (check) {
    if (next !== page) {
      console.error("exams/index.html is stale. Run: npm run build:exams");
      process.exit(1);
    }
    console.log("Exam panels are current.");
    return;
  }
  fs.writeFileSync(PAGE, next);
  console.log(`Wrote ${Math.round(Buffer.byteLength(next) / 1024)} KiB exams/index.html.`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) build();
